---
- hosts: "{{ node }}"
  become: yes
  #uncomment following if you want to run anible on same machine and keep node=localhost in ansible-playbook cmd
  connection: local
  gather_facts: yes
  tasks:
    - name: "copy dockerfile to server {{ node }}"
      copy:
        #change source address wrt your dockerfile location
        src: /home/hp1/Desktop/AnsibleDockerProject/Dockerfiles/dockerfile.tomcat
        dest: /tmp/dockerfile.tomcat

    - name: "copy war file to server {{ node }}"
      copy:
        src: /home/hp1/Desktop/AnsibleDockerProject/Dockerfiles/sample.war
        dest: /tmp/sample.war

    - name: "delete docker container tomcat if present"
      shell: "docker rm -f tomcat"
      ignore_errors: true

    - name: "delete docker image tomcat if already present"
      shell: "docker rmi tomcat"
      ignore_errors: true

    - name: "Build docker image tomcat"
      shell: "cd /tmp && docker build --no-cache -t tomcat -f dockerfile.tomcat ."

    - name: "Run docker image tomcat"
      shell: "docker run -d -p 8085:8080 --name tomcat tomcat"

# to run this playbook, change node and package_name value wrt yours
#for tomcat
#ansible-playbook tomcat.yml -i hosts -e "node=localhost"
#to see tomcat
#http://127.0.0.1:8085/<war_file_name>
