FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get install -y nginx
RUN echo '<h3>Hi, This is nginx page installed in Docker</h3>. ' \
>/usr/share/nginx/html/index.html
EXPOSE 80
ENTRYPOINT ["tail", "-f", "/dev/null"]
