FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get install -y nginx
RUN echo 'Hi, This is nginx page installed in Docker. ' \
>/usr/share/nginx/html/index.html
EXPOSE 80
CMD service nginx start && tail -f /dev/null

#docker build --no-cache -t nginx -f dockerfile.nginx .
#docker run -d -p 8085:8080 --name nginx nginx
#http://127.0.0.1:8084
